version: '3.8'

services:
  backend:
    build:
      context: ./my-nest-be
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=mysecretpassword
      - DB_NAME=mydatabase
    depends_on:
      - db

  frontend:
    build:
      context: ./my-next-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: